---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: instance
    image: ami-0bbe6b35405ecebdb
    instance_type: t2.micro
    vpc_subnet_id: subnet-b2e385fa
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: aws
verifier:
  name: testinfra
  lint:
    name: flake8
